### ISSUE TITLE
First result (right answer) appears twice in the list

### ISSUE THREAD

**Issue by thejoycekung** [AhoyLemon/idiots.win#7]
Screenshots for reference.

e.g. the query "why liberals"; the answer "...are stupid" appears twice
![image](https://cloud.githubusercontent.com/assets/13409103/16741483/6dc5110c-4771-11e6-9d18-e4dcb880407e.png)

![image](https://cloud.githubusercontent.com/assets/13409103/16741499/77c4eda8-4771-11e6-9a7f-581bf12787df.png)

**Comment by AhoyLemon** [comment]
Thanks.

I thought I had this fixed in a different update, but maybe I just wasn't seeing it under the right conditions. I'll take another look.

**Comment by ForsakenHarmony** [comment]
still a thing

**Comment by AhoyLemon** [comment]
@ForsakenHarmony, I'm closing this again cause I've tested this out a bunch and can't create the issue. If you can, let me know how.

**Comment by ForsakenHarmony** [comment]
it's not the top result here, but idk

![](https://i.imgur.com/3cUt6g8.png)

**Comment by ForsakenHarmony** [comment]
![](https://i.imgur.com/wkmfhHo.png)

**Comment by AhoyLemon** [comment]
Thanks @ForsakenHarmony.

I'm gonna leave this open and mark it `help wanted` because
1. I'm not sure why this would be and
2. I can't get those same responses. It's currently working for me and I never see dupes.

There's a bit in the `pullRequests()` function in the [_functions.js](https://github.com/AhoyLemon/idiots.win/blob/gh-pages/js/partials/_functions.js) partial that should be addressing this issue. Specifically...

```
$.each(data[1], function(key,value) {
  if (data[1][key][0] != myQuery) {
    if (n === 0) {
      correctAnswer = data[1][key][0];
    } else {
     answers.push([data[1][key][0], n]);
    }
    n++;
  }
});
```
Now what should be happening here is when it loops through to find incorrect answers, it checks that answer agaist the correct answer. If it's a match, it just skips to the next one.

So I'm wondering if there's some kind of normalization that would need to be done here to make those things match. Maybe there's an errant space or something. Can you try to see if one "how to attract a girl" is somehow a different string than the second "how to attract a girl"?
